<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"> 
	<head>  
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
														
<title></title> 

<link href="<?php echo $root ?>/css/screen.css" media="screen" rel="stylesheet" type="text/css" />

	</head> 
	<body>
        <div id="menu">
            <a id="logo" href="<?php echo $root ?>"><img src="<?php echo url('/css/images/logo.png') ?>" /></a>
            <form action="<?php echo url('/search') ?>/" method="post" accept-charset="utf-8">
                <p><input type="text" name="search" value="Search" id="search" size="9" class="autoClean">
                <input type="submit" value="&rarr;"></p>
            </form>
            <a href="http://www.seomoz.org">Thanks to Seomoz for its API</a>
        </div>
		<div id="container">
            <div id="header">
            </div>
            <div id="content">
                <?php include( $view ) ?>
            </div>
            <div id="footer">
            </div>
        </div>
        <script type="text/javascript" src="<?php echo $root ?>/js/jquery.js"></script>
        <script type="text/javascript" src="<?php echo $root ?>/js/jquery.tablesorter.js"></script>
        <script type="text/javascript" charset="utf-8">
            // Auto clean fields
            $(function () {

                $(".tablesorter").tablesorter({sortList: [[2,1], [3,1]]}); 

                $(".autoClean").focus(function() {
                    if( $(this).attr('inited') != "inited" ){
                        $(this).val('');
                        $(this).attr('inited', "inited" );
                    }
                })

            });
            
        </script>
    </body>
</body>